import type { AssignmentMap } from '../types/seat.types';

/**
 * Maps seatCode → employeeId
 * Seat codes are generated by seatUtils.generateReadableSeatMetadata.
 * These are sample assignments for the mock/prototype phase.
 */
export const mockAssignments: AssignmentMap = {
  'A1':  1,   // Akash Sharma     → top-zone seat 1
  'A3':  2,   // Priya Singh
  'A5':  3,   // Rahul Verma
  'A7':  4,   // Sneha Reddy
  'B1':  5,   // Amit Patel       → middle-zone seat 1
  'B3':  6,   // Neha Gupta
  'B5':  7,   // Rohan Mehta
  'B7':  8,   // Pooja Iyer
  'B9':  9,   // Vikram Nair
  'B11': 10,  // Divya Krishnan
  'C1':  11,  // Arjun Bose       → second middle zone
  'C3':  12,  // Meera Joshi
  'C5':  13,  // Suresh Pillai
  'D1':  14,  // Anita Desai      → bottom zone
  'D3':  15,  // Karthik Raj
};
